### PR TITLE
link to the forward URL

### PR DESCRIPTION
**Pull request by lofwyr14**

### CODE REVIEW

**Review by bohmber — APPROVED** [review]
+1

**Comment by tandraschko** [comment]
@bohmber looks like any of the changes crashed the hompeage? https://myfaces.apache.org/#/coreReleaseChecklist looks lite it loads our new and old homepage
can you please check this?

**Comment by bohmber** [comment]
> @bohmber looks like any of the changes crashed the hompeage? https://myfaces.apache.org/#/coreReleaseChecklist looks lite it loads our new and old homepage
> can you please check this?

It looks like someone has updated the homepage in svn as well? If you look at the published content you will see it. The content in git looks good i don't know how to fix it. We didn't switch off the svn content?

**Comment by tandraschko** [comment]
@bohmber you were right, i talked with the infra and they fixed it. thanks!

**Comment by bohmber** [comment]
Thanks @tandraschko

**Pull request merged**
