### PR TITLE
Improved MyFaces Homepage

### PR DESCRIPTION
**Pull request by bohmber**
Fixed Tobago pages and some other pages
Simplify menu
Added required ASF pages

You can review the changes here https://bohmber.github.io/myfaces-homepage/

### CODE REVIEW

**Comment by tandraschko** [comment]
The items below "core concepts" are to long now:
Apache MyFaces Core Concepts - View Pooling

that doesnt look good, same for versions.
We are already under Core / Versions, why does the submenus are called "Apache MyFaces Core 1.1"?

**Comment by tandraschko** [comment]
Also the core concepts page is to fat now for me, it was by design to put it in different views as e.g. viewpooling or immediate are really really big.

**Comment by bohmber** [comment]
The menu structure should be better. 
And I don't like a menu item for every old version. 
It will not scale for the MyFaces homepage.
What about this? An old Version page and pages for the active versions.

I changed the Concept page. The Concept page doesn't include the concept directly. Better now?

**Comment by tandraschko** [comment]
concept looks better now.

hmm, really unsure. 
maybe all versions in one single view and outsource the config section, to have one view for each version with just config stuff?

**Comment by bohmber** [comment]
Ok i will play with the version pages a little bit. There might be a better solution

**Comment by bohmber** [comment]
How about this?

https://bohmber.github.io/myfaces-homepage/

**Comment by tandraschko** [comment]
thats ok for me, just 2.2 is doubled now

**Comment by bohmber** [comment]
fixed

**Comment by bohmber** [comment]
I would like to rename concepts to improvements? Just an idea?

**Comment by tandraschko** [comment]
unsure
its more a mix of internal concepts, improvements and how JSF works (like immediate)

**Comment by bohmber** [comment]
At the moment i'm fine with concepts. Can we merge now?

**Comment by tandraschko** [comment]
+1

**Pull request merged**
